Lab 5: Show new contacts on parent component list and fix validation error
=> onSubmit calls createContact and passes the event that EventEmitter sent out (a new contact). createContact then adds this new contact to the list and it shows automatically on the screen.

core.js:4352 ERROR TypeError: Cannot read property 'minlength' of null
Fix missing "?" when checking validation!!!